# Generated by Django 6.0.3 on 2026-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('iftar_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
